const data = [
  {
    id: 1,
    name: "Smartphone",
    category: "Gadgets",
    price: 306.66,
    rating: 4.9,
    stock: 63,
  },
  {
    id: 2,
    name: "Laptop",
    category: "Anime Toys",
    price: 355.92,
    rating: 3.1,
    stock: 48,
  },
  {
    id: 3,
    name: "Headphones",
    category: "Clothing",
    price: 486.97,
    rating: 1.1,
    stock: 51,
  },
  {
    id: 4,
    name: "Smartwatch",
    category: "Anime Toys",
    price: 247.47,
    rating: 1.2,
    stock: 80,
  },
  {
    id: 5,
    name: "Camera",
    category: "Gadgets",
    price: 386.4,
    rating: 2.7,
    stock: 58,
  },
  {
    id: 6,
    name: "T-Shirt",
    category: "Anime Toys",
    price: 96.99,
    rating: 2.9,
    stock: 57,
  },
  {
    id: 7,
    name: "Jeans",
    category: "Electronics",
    price: 375.49,
    rating: 3.3,
    stock: 6,
  },
  {
    id: 8,
    name: "Jacket",
    category: "Clothing",
    price: 419.47,
    rating: 3.6,
    stock: 26,
  },
  {
    id: 9,
    name: "Sneakers",
    category: "Clothing",
    price: 319.05,
    rating: 4.4,
    stock: 46,
  },
  {
    id: 10,
    name: "Boots",
    category: "Shoes",
    price: 149.19,
    rating: 2.3,
    stock: 11,
  },
  {
    id: 11,
    name: "Gaming Console",
    category: "Electronics",
    price: 102.48,
    rating: 4.1,
    stock: 97,
  },
  {
    id: 12,
    name: "Bluetooth Speaker",
    category: "Anime Toys",
    price: 262.99,
    rating: 2.0,
    stock: 85,
  },
  {
    id: 13,
    name: "Drone",
    category: "Clothing",
    price: 260.83,
    rating: 4.0,
    stock: 42,
  },
  {
    id: 14,
    name: "Tablet",
    category: "Electronics",
    price: 101.03,
    rating: 4.9,
    stock: 50,
  },
  {
    id: 15,
    name: "Charger",
    category: "Clothing",
    price: 276.72,
    rating: 1.8,
    stock: 100,
  },
  {
    id: 16,
    name: "Anime Figure",
    category: "Anime Toys",
    price: 341.95,
    rating: 1.3,
    stock: 76,
  },
  {
    id: 17,
    name: "Action Figure",
    category: "Anime Toys",
    price: 93.14,
    rating: 2.1,
    stock: 92,
  },
  {
    id: 18,
    name: "Plush Toy",
    category: "Shoes",
    price: 276.11,
    rating: 2.1,
    stock: 42,
  },
  {
    id: 19,
    name: "Backpack",
    category: "Clothing",
    price: 440.22,
    rating: 4.8,
    stock: 95,
  },
  {
    id: 20,
    name: "Cap",
    category: "Electronics",
    price: 366.88,
    rating: 3.2,
    stock: 26,
  },
  {
    id: 21,
    name: "Sunglasses",
    category: "Gadgets",
    price: 378.03,
    rating: 4.3,
    stock: 65,
  },
  {
    id: 22,
    name: "Wallet",
    category: "Shoes",
    price: 65.82,
    rating: 4.7,
    stock: 25,
  },
  {
    id: 23,
    name: "Earbuds",
    category: "Anime Toys",
    price: 293.39,
    rating: 4.0,
    stock: 36,
  },
  {
    id: 24,
    name: "Mouse",
    category: "Anime Toys",
    price: 28.51,
    rating: 3.8,
    stock: 66,
  },
  {
    id: 25,
    name: "Keyboard",
    category: "Anime Toys",
    price: 336.4,
    rating: 2.0,
    stock: 5,
  },
  {
    id: 26,
    name: "Power Bank",
    category: "Anime Toys",
    price: 16.6,
    rating: 2.0,
    stock: 61,
  },
  {
    id: 27,
    name: "Jumper",
    category: "Shoes",
    price: 198.26,
    rating: 4.0,
    stock: 35,
  },
  {
    id: 28,
    name: "Dress",
    category: "Electronics",
    price: 383.9,
    rating: 4.7,
    stock: 77,
  },
  {
    id: 29,
    name: "Sneaker Shoes",
    category: "Gadgets",
    price: 140.59,
    rating: 4.7,
    stock: 37,
  },
  {
    id: 30,
    name: "LED Lamp",
    category: "Gadgets",
    price: 458.6,
    rating: 3.9,
    stock: 79,
  },
];

//TODO: filter === Electronics
//TODO: sort by rating
//TODO: slice top 3
//TODO: map transform object shape to {name: "name"}

const filterElectronicP = data
  .filter((item) => item.category === "Electronics")
  .sort((a, b) => b.rating - a.rating)
  .slice(0, 4)
  .map((item) => {
    return { name: item.name };
  });

console.log(filterElectronicP);
